highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "End on End"
tagline: ""
description: "Follow <a href=\"https://micro.blog/endonend\">@endonend on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/endonend\">@endonend on Micro.blog</a>."
baseurl: ""
url: "https://www.endonend.org"
markdown: "kramdown"
username: "endonend"
microblog_user: "endonend"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "End on End"
name: "End on End"
gravatar_hash: "24d2b5e528301b53a5c6720613570978"
avatar: "https://micro.blog/endonend/avatar.jpg"
full_name: "End on End"
bio: ""
twitter_username: "endonend"
github_username: "endonend"
instagram_username: "endonend"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "1644"
gems: ["jekyll-paginate"]
itunes_description: "Buffalo, NY // UX Designer/Business Analyst  // Partner + Rails developer with Relic Scout  //  Interests: comics, music, Nintendo Switch, hockey, buddhism, Apple, cooking, and photography. He/him.

"
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Jason Dettbarn"
itunes_email: ""
podcast: false