# Dependencies
# - markdown:         redcarpet
highlighter:      pygments

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Jason Dettbarn"
tagline: ""
description: "Follow <a href=\"https://micro.blog/endonend\">@endonend on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/endonend\">@endonend on Micro.blog</a>."
baseurl: ""
url: "http://micro.endonend.org"
markdown: "kramdown"
username: "endonend"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Jason Dettbarn"
name: "Jason Dettbarn"
gravatar_hash: "24d2b5e528301b53a5c6720613570978"
avatar: "https://www.gravatar.com/avatar/24d2b5e528301b53a5c6720613570978?s=160"
full_name: "Jason Dettbarn"
bio: ""
twitter_username: "endonend"
github_username: "endonend"
instagram_username: "endonend"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"